[package]
name = "sahomedb"
version = "0.1.0-alpha.2"
edition = "2021"

[dependencies]
rayon = "1.8.0"
parking_lot = "0.12.1"
ordered-float = "4.2.0"
rand = "0.8.5"

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde-big-array = "0.5.1"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1