[package]
name = "sahomedb"
version = "0.1.0-beta.3"
edition = "2021"

# Information.
license = "Apache-2.0"
authors = ["Elijah Obs", "Samson"]
description = "Fast embedded vector database with incremental HNSW indexing."
homepage = "https://sahome.com/"
repository = "https://github.com/Sahomey-Technologies/sahomedb"

# Metadata.
keywords = ["embedded", "vector", "database", "hnsw", "ann"]
categories = ["database", "algorithms", "embedded"]

[dependencies]
sled = "0.34.7"

# Utilities.
rayon = "1.8.0"
parking_lot = "0.12.1"
ordered-float = "4.2.0"
rand = "0.8.5"

# Serialization.
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde-big-array = "0.5.1"
bincode = "1.3.3"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1