[package]
name = "sahomedb"
version = "0.1.0-alpha.2"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
itertools = "0.12.0"
rand = "0.8.5"

serde = "1.0.193"
serde_json = "1.0.108"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1