blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/Sahomey-Technologies/sahomedb/discussions
    about: Ask general questions or share ideas on Discussions.