name: Quality check and testing

# Summary of the workflow
# For every push to the main branch or any pull request:
# 1. Run cargo clippy: Check linting to improve code quality.
# 2. Run cargo test: Run all tests.

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAHOMEDB_TOKEN: token
  SAHOMEDB_DIMENSION: 2

jobs:
  clippy-lint:
    name: Lint code with Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  run-tests:
    name: Run all tests
    needs: clippy-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test